# Generated by Django 5.1.3 on 2024-11-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appel', '0002_presence'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='total_absences',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='total_presences',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='presence',
            unique_together={('etudiant', 'date')},
        ),
    ]
