# Generated by Django 5.1.3 on 2026-04-15 11:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appel', '0003_etudiant_total_absences_etudiant_total_presences_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='date_inscription',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='numero_etudiant',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='filiere',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filiere',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='filiere',
            name='salle',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterModelOptions(
            name='presence',
            options={'ordering': ['-date', 'etudiant__nom']},
        ),
    ]
