# Generated by Django 5.2.13 on 2026-04-15 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appel', '0004_upgrade_classroom_management'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etudiant_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AbsenceJustification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=150)),
                ('details', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvee'), ('rejected', 'Refusee')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('presence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='justification', to='appel.presence')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
